src/Entity/Tache.php
<?php

namespace App\Entity;

use App\Repository\TacheRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TacheRepository::class)]
class Tache
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Statut = null;

    #[ORM\Column]
    private ?date $Date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->Statut;
    }

    public function setStatut(string $Statut): self
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->Date;
    }

    public function setDate(string $Date): self
    {
        $this->Date = $Date;

        return $this;
    }


    
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
class Utilisateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }
}

src/Form/AjoutTacheType.php
<?php

namespace App\Form;

use App\Entity\Tache;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AjoutTacheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Titre')
            ->add('Description')
            ->add('Statut')
            ->add('Date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tache::class,
        ]);
    }
}

src/Controller/TacheController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TacheController extends AbstractController
{
    ///affiche la liste
    #[Route('/', name: 'home.index')]
    public function home(ArticleRepository $repository): Response
    {
      
        //return $this->render('tache/index.html.twig');
        /*** */
        //$taches = ['tache 1', 'tache 2', 'tache 3'];
        //return $this->render('taches/index.html.twig', ['taches' => $taches]);
        /***** */
        // mettre dans le tableau $taches
        #$taches= $this->getDoctrine()->getRepository(Article::class)->findAll();
        return $this->render('taches/index.html.twig',['taches'=>$repository-> findAll()]);
    }

    /*#[Route('/tache/save', name: 'tache.save')]
    public function save(EntityManagerInterface $entityManager): Response
    {
        $tache = new Tache();
        $tache->setTitre('Tache 1');
        $tache->setDescription("aaa");
        $tache->setDate("02/01/2022");
        $entityManager->persist($tache);
        $entityManager->flush();
        return new Response('Tache enregistré avec l\'identifiant ' . $tache->getId());
    }*/



   

}

templates/ajout.html.twig
{% extends 'base.html.twig' %}
{% block title %}Ajouter Tache{% endblock %}
{% block body %}
{{ form_start(form) }}
{{ form_widget(form) }}
 <button type="submit" class="btn btn-success">Créer</button>
{{ form_end(form) }}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ tache.titre }}{% endblock %}
{% block body %}
<h1>{{ tache.titre }}</h1>
<p>{{ tache.description }}</p>
<select><option>{{ tache.statut }}</option></select>
<p>{{ tache.date }}</p>
<hr>
<a href="/">Retour</a>
{% endblock %}

templates/tache/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TacheController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/bourg/examen_sy/src/Controller/TacheController.php'|file_link(0) }}">src/Controller/TacheController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/bourg/examen_sy/templates/tache/index.html.twig'|file_link(0) }}">templates/tache/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}